version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # RabbitMQ main port
      - '15672:15672' # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  # exex_manager_js:
  #   image: exex_manager_js # Use the tag you used for your local build
  #   container_name: exex_manager_js
  #   build:
  #     context: ./js_build # Specify the build context
  #   depends_on:
  #     - rabbitmq # Ensure RabbitMQ starts before this service
  #   environment:
  #     RABBITMQ_URL: amqp://user:password@rabbitmq:5672 # URL to access RabbitMQ
  #   ports:
  #     - '3000:3000' # Example port mapping for your app, adjust as necessary

  exex_manager:
    image: exex_manager # Use the tag you used for your local build
    container_name: exex_managers
    build:
      context: ../rambda_exex_manager # Specify the build context
    depends_on:
      - rabbitmq # Ensure RabbitMQ starts before this service
      - postgres
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672 # URL to access RabbitMQ
      POSTGRES_URL: postgresql://user:password@postgres:5432/rambda # URL to access RabbitMQ
      DOCKER_SOCKET_PATH: /var/run/docker.sock
      ABSOLUTE_DATA_FILE_PATH: /Users/dimitridumonet/Code/rambda/shared_data
    ports:
      - '3000:3000' # Example port mapping for your app, adjust as necessary
    # Map docker runner from outside the container in the container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Replace with host file system, should be same as above
      - /Users/dimitridumonet/Code/rambda/shared_data:/app/shared_data
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rambda
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
